### PR TITLE
Fix Duplicate Interface List Bug (15)

### LINKED ISSUE #15: Duplicate Interface Names With OneOf Tag
There is a bug where multiple interfaces of the same name are added to base classes of abstract types.

For example:
```
  class BaseA
   class ImplementationA: BaseA
```
In the above example, during normal syntax tree parsing, Yardarm will generate the class `BaseA` as `IBaseA` and `ImplementationA` will inherti `IBaseA`. If a one of tag and discriminator values/mappings are provided, it will add a Discriminator attribute in the client project that will then be able to parse abstract classes to the implementations as expected.

Current issue is during the enrichment of the syntax tree with the Base Type Enricher. It uses the context repository to pull a given base type syntax list and adds that to what is currently provided on the syntax tree. The issue is during normal syntax parsing, `ImplementationA` will already have the proper syntax: `ImplementationA:IBaseA`, but the enricher will, without care, add a second `IBaseA`, thus causing the following syntax tree: `ImplementationA:IBaseA,IBaseA`

C# will then have a bad day due to a complaint about there being multiple interfaces of the same name being added to the interface list

### PR DESCRIPTION
**Pull request by mmmasent**
Motivation
----
Current Yardarm SDK generation crashes when using discriminators and one of tags due to a Duplicate interface name being added to the syntax list for a given class.

Modifications
----
* Updated BaseTypeEnricher to check if a given interface name exists in the syntax list before blindingly adding it

Result
----
Yardarm should no longer crash when generating sdks with discriminators and one of tags

Fixes #15

### CODE REVIEW

File: src/Yardarm/Enrichment/Schema/Internal/BaseTypeEnricher.cs [hunk 1]
```diff
@@ -28,6 +28,13 @@ public BaseTypeEnricher(GenerationContext context)
 
             BaseTypeSyntax[] additionalBaseTypes = feature.GetBaseTypes(context.LocatedElement).ToArray();
 
+            if (target.BaseList != null)
+            {
+                additionalBaseTypes = additionalBaseTypes.Where(additionalBaseType =>
+                    !target.BaseList.Types.Any(currentType => additionalBaseType.ToString() == currentType.ToString()))
```
Comment (brantburnett) [inline src/Yardarm/Enrichment/Schema/Internal/BaseTypeEnricher.cs:34]: Is a string comparison the best option we have here? I feel like there should be a cleaner way, this might not account well for namespaces.

Also, I'd drop the ToArray above and make additionalBaseTypes an IEnumerable. Then we don't need to allocate a second array here, we can just do it below in the call to AddBaseListTypes.

**Review by brantburnett — CHANGES_REQUESTED** [review]

File: src/Yardarm/Enrichment/Schema/Internal/BaseTypeEnricher.cs (hunk 1 above)
Comment (mmmasent) [reply src/Yardarm/Enrichment/Schema/Internal/BaseTypeEnricher.cs]: Updated per your suggestions

**Review by brantburnett — APPROVED** [review]
